/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GraficoSecaoP;

/**
 *
 * @author caricelucena
 */
public class Tre extends javax.swing.JFrame {

    /**
     * Creates new form Tre
     */
    public Tre() {
        initComponents();
        setSize(1224, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PainelTrabalho = new javax.swing.JDesktopPane();
        BarradeMenu = new javax.swing.JMenuBar();
        tre = new javax.swing.JMenu();
        Home = new javax.swing.JMenuItem();
        fechar = new javax.swing.JMenuItem();
        apuracaoSecao = new javax.swing.JMenu();
        prefeitoSecao = new javax.swing.JMenuItem();
        governadorSecao = new javax.swing.JMenuItem();
        apuracao = new javax.swing.JMenu();
        prefeitoApuracao = new javax.swing.JMenuItem();
        governadorapuracao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 240, 140, 150);
        getContentPane().add(PainelTrabalho);
        PainelTrabalho.setBounds(0, -1, 1270, 740);

        tre.setForeground(new java.awt.Color(0, 0, 0));
        tre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application_osx_terminal.png"))); // NOI18N
        tre.setText("TRE");

        Home.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 0, 0));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application_osx_terminal.png"))); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        tre.add(Home);

        fechar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fechar.setForeground(new java.awt.Color(0, 0, 0));
        fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });
        tre.add(fechar);

        BarradeMenu.add(tre);

        apuracaoSecao.setForeground(new java.awt.Color(0, 0, 0));
        apuracaoSecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder_table.png"))); // NOI18N
        apuracaoSecao.setText("Apuração Seções");

        prefeitoSecao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prefeitoSecao.setForeground(new java.awt.Color(0, 0, 0));
        prefeitoSecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_go.png"))); // NOI18N
        prefeitoSecao.setText("Prefeito");
        prefeitoSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefeitoSecaoActionPerformed(evt);
            }
        });
        apuracaoSecao.add(prefeitoSecao);

        governadorSecao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        governadorSecao.setForeground(new java.awt.Color(0, 0, 0));
        governadorSecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        governadorSecao.setText("Governador");
        governadorSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governadorSecaoActionPerformed(evt);
            }
        });
        apuracaoSecao.add(governadorSecao);

        BarradeMenu.add(apuracaoSecao);

        apuracao.setForeground(new java.awt.Color(0, 0, 0));
        apuracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart_bar.png"))); // NOI18N
        apuracao.setText("Apuração");

        prefeitoApuracao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prefeitoApuracao.setForeground(new java.awt.Color(0, 0, 0));
        prefeitoApuracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        prefeitoApuracao.setText("Prefeito");
        prefeitoApuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefeitoApuracaoActionPerformed(evt);
            }
        });
        apuracao.add(prefeitoApuracao);

        governadorapuracao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        governadorapuracao.setForeground(new java.awt.Color(0, 0, 0));
        governadorapuracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_go.png"))); // NOI18N
        governadorapuracao.setText("Governador");
        governadorapuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governadorapuracaoActionPerformed(evt);
            }
        });
        apuracao.add(governadorapuracao);

        BarradeMenu.add(apuracao);

        setJMenuBar(BarradeMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prefeitoSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefeitoSecaoActionPerformed
        JanelaSecaoP graficoP = new JanelaSecaoP();
        graficoP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prefeitoSecaoActionPerformed

    private void governadorapuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governadorapuracaoActionPerformed
              JanelaApuracaoG apuracaoG = new JanelaApuracaoG();
              apuracaoG.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_governadorapuracaoActionPerformed

    private void governadorSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governadorSecaoActionPerformed

        JanelaSecaoG graficoG = new JanelaSecaoG();
        graficoG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_governadorSecaoActionPerformed

    private void prefeitoApuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefeitoApuracaoActionPerformed
      JanelaApuracaoP apuracaoP = new JanelaApuracaoP();
      apuracaoP.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_prefeitoApuracaoActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
       Tre tre = new Tre();
       tre.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeMenu;
    private javax.swing.JMenuItem Home;
    private javax.swing.JDesktopPane PainelTrabalho;
    private javax.swing.JMenu apuracao;
    private javax.swing.JMenu apuracaoSecao;
    private javax.swing.JMenuItem fechar;
    private javax.swing.JMenuItem governadorSecao;
    private javax.swing.JMenuItem governadorapuracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem prefeitoApuracao;
    private javax.swing.JMenuItem prefeitoSecao;
    private javax.swing.JMenu tre;
    // End of variables declaration//GEN-END:variables
}
